### ISSUE TITLE
Changing the bounds leads to a weird behaviour

### ISSUE THREAD

**Issue by PhilippMarquardt** [martinzlocha/anchor-optimization#8] opened 2019-11-07 11:41 UTC
Hi!
First of all thanks for the contribution. In the default configuration the script worked out fine for me. I have a dataset with very small rectangles (256x256 images with small objects on it). For that reason I changed to bounds to allow a smaller value (I changed it here: https://github.com/martinzlocha/anchor-optimization/blob/master/optimize_anchors.py#L174) which worked fine and it printed that there are only 9 labels without a matching anchor, which is very good for my 2000+ images dataset. The full print here: 

```
Current best anchor configuration
Ratios: [0.343, 0.77, 1.0, 1.298, 2.916]
Scales: [0.103, 0.129, 0.164]
Number of labels that don't have any matching anchor: 9
```

I ran your script like this:

```
python optimize_anchors.py --image-max-side 256 --image-min-side 256 --ratios 5 dataset.csv
```

But when I plug these values in the config and run the debug.py script from keras-retinanet like this: 
```
 python keras_retinanet/bin/debug.py --image-min-side 256 --image-max-side 256 --config config.ini csv dataset.csv classes.csv
```
very many boxes are drawn red (much more than half of the boxes of my full dataset). 

**Is there a limitation for the bounds of the scales that I don't know about?** 
Thanks in advance

**Comment by martinzlocha** [comment] 2019-11-08 19:26
Hi, thank you very much for the detailed issue. From the scales I am guessing that your boxes are 3-5px large in general?

The issue is that the smallest stride is 8px (the stride defines the spacing between anchor boxes). If the anchor boxes are smaller than your stride you won't have good coverage of the image and if the ground truth falls inbetween the anchor boxes the object won't ever be detected.

With the flags that you passed in the anchor optimization tool ignores the stride during the optimization process and simply assumes that the center of the ground truth is the same as the center of the anchor box. The assumption is fine when the ground truth boxes are larger however for very small objects this causes a larger error. You can also use strides in the computation by using the `include-stride` flag however the computation will be much slower. (Side note: there is room for optimization.) This should however be fine for your dataset as its not too large.

Even if you include stride in your calculation I don't think that you will get great results. The scale bounds of 0.4 and 2 are sensible defaults in my opinion as it will make the smallest anchors approximately 12px large and this will mean that the anchor boxes will partially overlap which is beneficial (as there are no "blind spots"). You might want to try scaling up your images to get better results.

Hope this explanation makes a bit of sense, let me know if you have any other questions. Also if you have any suggestions on how the README could be made clearer on this issue please feel free to create a PR.

**Comment by martinzlocha** [comment] 2019-11-20 20:45
Closing now, if you have other questions please ask.

**Closed by martinzlocha** 2019-11-20 20:45 UTC

**Comment by 2696120622** [comment] 2019-12-16 01:10
> Hi, thank you very much for the detailed issue. From the scales I am guessing that your boxes are 3-5px large in general?
> 
> The issue is that the smallest stride is 8px (the stride defines the spacing between anchor boxes). If the anchor boxes are smaller than your stride you won't have good coverage of the image and if the ground truth falls inbetween the anchor boxes the object won't ever be detected.
> 
> With the flags that you passed in the anchor optimization tool ignores the stride during the optimization process and simply assumes that the center of the ground truth is the same as the center of the anchor box. The assumption is fine when the ground truth boxes are larger however for very small objects this causes a larger error. You can also use strides in the computation by using the `include-stride` flag however the computation will be much slower. (Side note: there is room for optimization.) This should however be fine for your dataset as its not too large.
> 
> Even if you include stride in your calculation I don't think that you will get great results. The scale bounds of 0.4 and 2 are sensible defaults in my opinion as it will make the smallest anchors approximately 12px large and this will mean that the anchor boxes will partially overlap which is beneficial (as there are no "blind spots"). You might want to try scaling up your images to get better results.
> 
> Hope this explanation makes a bit of sense, let me know if you have any other questions. Also if you have any suggestions on how the README could be made clearer on this issue please feel free to create a PR.

Which value of --no-resize will give a better result, True of False?
It looks like that True (i.e. resizing the bounding box) is better.
